version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    networks:
      - ai_saas_app_backend
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  ai_saas_app_backend:

volumes:
  postgres:
    name: ai-saas-postgres
