version: '3.8'
services:
  postgres:
    image: postgres:13.5
    container_name: postgres
    restart: always
    networks:
      - ai_app_backend
    ports:
      - '5432:5432'
    env_file:
      - .env

networks:
  ai_app_backend:

volumes:
  postgres:
    name: ai-postgres
