version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-sass-app-image
    command: node ./dist/apps/api-gateway/main
    ports:
      - '9000:9000'
    networks:
      - ai_saas_app_backend
    env_file:
      - .env
      - .env.production
    environment:
      - NODE_ENV=production
    labels:
      - 'traefik.http.routers.blog.rule=Host(`traefik.io`) || (Host(`containo.us`) && Path(`/traefik`))'

  user-svc:
    image: ai-sass-app-image
    ports:
      - '50051:50051'
    networks:
      - ai_saas_app_backend
    env_file:
      - .env
      - .env.production
    environment:
      - NODE_ENV=production
    command: node ./dist/apps/user-svc/main
    healthcheck:
      test: ['CMD', 'grpc_health_probe', '-addr=localhost:50051']
      interval: 10s
      timeout: 3s
      retries: 3
    labels:
      - 'traefik.http.routers.blog.rule=Host(`traefik.io`) || (Host(`containo.us`) && Path(`/traefik`))'

  ai-svc:
    image: ai-sass-app-image
    ports:
      - '50052:50052'
    networks:
      - ai_saas_app_backend
    env_file:
      - .env
      - .env.production
    environment:
      - NODE_ENV=production
    command: node ./dist/apps/ai-svc/main
    healthcheck:
      test: ['CMD', 'grpc_health_probe', '-addr=localhost:50052']
      interval: 10s
      timeout: 3s
      retries: 3
    labels:
      - 'traefik.http.routers.blog.rule=Host(`traefik.io`) || (Host(`containo.us`) && Path(`/traefik`))'

networks:
  ai_saas_app_backend:
